"""Generate dbt SQL models and schema.yml from a PipelineSpec."""
from __future__ import annotations

import textwrap
from typing import Optional

import yaml

from ..dsl.ir import PipelineSpec, TransformNode
from ..dsl.types import AggFunction, TransformType
from ..compiler.selector import Target
from .base import BaseTarget, CompiledArtifact


_AGG_SQL = {
    AggFunction.COUNT: "COUNT",
    AggFunction.SUM: "SUM",
    AggFunction.AVG: "AVG",
    AggFunction.MIN: "MIN",
    AggFunction.MAX: "MAX",
    AggFunction.FIRST: "MIN",      # dbt/SQL doesn't have FIRST; use MIN as proxy
    AggFunction.LAST: "MAX",
    AggFunction.COLLECT_LIST: "ARRAY_AGG",
    AggFunction.COUNT_DISTINCT: "COUNT(DISTINCT",
}


class DbtTarget(BaseTarget):
    def generate(self, spec: PipelineSpec) -> CompiledArtifact:
        files: dict[str, str] = {}
        compiled_nodes: list[dict] = []

        for node in spec.topological_order():
            if node.is_source():
                continue  # sources become dbt sources, not models

            sql, meta = self._node_to_sql(node, spec)
            model_name = node.name
            files[f"models/{model_name}.sql"] = sql
            compiled_nodes.append(meta)

        files["models/schema.yml"] = self._generate_schema_yml(spec)
        files["dbt_project.yml"] = self._generate_dbt_project(spec)
        files["models/sources.yml"] = self._generate_sources_yml(spec)

        return CompiledArtifact(
            target=Target.DBT,
            spec_name=spec.name,
            files=files,
            compiled_nodes=compiled_nodes,
        )

    # ─── SQL model generators ───────────────────────────────────

    def _node_to_sql(self, node: TransformNode, spec: PipelineSpec) -> tuple[str, dict]:
        meta = {
            "name": node.name,
            "transform_type": node.transform_type.value,
            "inputs": node.inputs,
            "predicate": node.predicate,
            "columns": node.columns,
            "group_by": node.group_by,
            "aggregations": [
                {"name": a.output_name, "function": a.function.value, "column": a.column}
                for a in node.aggregations
            ],
            "join_type": node.join_type.value if node.join_on else None,
            "join_on": node.join_on,
        }

        header = (
            f"{{# Auto-generated by pipeline-topology-compiler #}}\n"
            f"{{# Pipeline: {spec.name} | Node: {node.name} #}}\n\n"
        )

        if node.transform_type == TransformType.FILTER:
            sql = self._filter_sql(node, spec)
        elif node.transform_type == TransformType.SELECT:
            sql = self._select_sql(node, spec)
        elif node.transform_type == TransformType.MAP:
            sql = self._map_sql(node, spec)
        elif node.transform_type == TransformType.JOIN:
            sql = self._join_sql(node, spec)
        elif node.transform_type == TransformType.AGGREGATE:
            sql = self._aggregate_sql(node, spec)
        elif node.transform_type == TransformType.UNION:
            sql = self._union_sql(node, spec)
        elif node.transform_type == TransformType.SINK:
            sql = self._sink_sql(node, spec)
        else:
            sql = f"-- TODO: {node.name} ({node.transform_type.value})\nSELECT 1"

        return header + sql, meta

    def _ref(self, node_name: str, spec: PipelineSpec) -> str:
        """Return {{ ref('x') }} for transform nodes, {{ source('pipeline', 'x') }} for source nodes."""
        if node_name in spec.nodes and spec.nodes[node_name].is_source():
            return "{{ " + f"source('{spec.name}', '{node_name}')" + " }}"
        return "{{ " + f"ref('{node_name}')" + " }}"

    def _filter_sql(self, node: TransformNode, spec: PipelineSpec) -> str:
        inp = self._ref(node.inputs[0], spec)
        return (
            f"with source as (\n"
            f"    select * from {inp}\n"
            f"),\n\n"
            f"filtered as (\n"
            f"    select *\n"
            f"    from source\n"
            f"    where {node.predicate}\n"
            f")\n\n"
            f"select * from filtered\n"
        )

    def _select_sql(self, node: TransformNode, spec: PipelineSpec) -> str:
        inp = self._ref(node.inputs[0], spec)
        cols = ",\n    ".join(node.columns or ["*"])
        return (
            f"with source as (\n"
            f"    select * from {inp}\n"
            f"),\n\n"
            f"projected as (\n"
            f"    select\n"
            f"        {cols}\n"
            f"    from source\n"
            f")\n\n"
            f"select * from projected\n"
        )

    def _map_sql(self, node: TransformNode, spec: PipelineSpec) -> str:
        inp = self._ref(node.inputs[0], spec)
        extra_cols = ",\n    ".join(f"{expr} as {col}" for col, expr in node.expressions.items())
        return (
            f"with source as (\n"
            f"    select * from {inp}\n"
            f"),\n\n"
            f"mapped as (\n"
            f"    select\n"
            f"        *,\n"
            f"        {extra_cols}\n"
            f"    from source\n"
            f")\n\n"
            f"select * from mapped\n"
        )

    def _join_sql(self, node: TransformNode, spec: PipelineSpec) -> str:
        left_name, right_name = node.inputs[0], node.inputs[1]
        left_ref = self._ref(left_name, spec)
        right_ref = self._ref(right_name, spec)
        jtype = node.join_type.value.upper()
        on = node.join_on or f"{left_name}.id = {right_name}.id"
        return (
            f"with left_cte as (\n"
            f"    select * from {left_ref}\n"
            f"),\n\n"
            f"right_cte as (\n"
            f"    select * from {right_ref}\n"
            f"),\n\n"
            f"joined as (\n"
            f"    select\n"
            f"        left_cte.*,\n"
            f"        right_cte.*\n"
            f"    from left_cte\n"
            f"    {jtype} join right_cte\n"
            f"        on {on}\n"
            f")\n\n"
            f"select * from joined\n"
        )

    def _aggregate_sql(self, node: TransformNode, spec: PipelineSpec) -> str:
        inp = self._ref(node.inputs[0], spec)
        gb_cols = ",\n        ".join(node.group_by) if node.group_by else None
        agg_exprs = []
        for a in node.aggregations:
            fn = _AGG_SQL.get(a.function, "COUNT")
            col = a.column or "*"
            if a.function == AggFunction.COUNT_DISTINCT:
                agg_exprs.append(f"COUNT(DISTINCT {col}) as {a.output_name}")
            else:
                agg_exprs.append(f"{fn}({col}) as {a.output_name}")

        select_parts = []
        if node.group_by:
            select_parts.extend(node.group_by)
        select_parts.extend(agg_exprs)
        select_str = ",\n        ".join(select_parts)

        gb_clause = f"\n    group by\n        {gb_cols}" if gb_cols else ""

        return (
            f"with source as (\n"
            f"    select * from {inp}\n"
            f"),\n\n"
            f"aggregated as (\n"
            f"    select\n"
            f"        {select_str}\n"
            f"    from source"
            f"{gb_clause}\n"
            f")\n\n"
            f"select * from aggregated\n"
        )

    def _union_sql(self, node: TransformNode, spec: PipelineSpec) -> str:
        parts = "\nunion all\n".join(
            f"select * from {self._ref(inp, spec)}" for inp in node.inputs
        )
        return f"{parts}\n"

    def _sink_sql(self, node: TransformNode, spec: PipelineSpec) -> str:
        inp = self._ref(node.inputs[0], spec)
        return (
            f"-- Final model written to warehouse table: {node.name}\n"
            f"select * from {inp}\n"
        )

    # ─── Config file generators ──────────────────────────────────

    def _generate_schema_yml(self, spec: PipelineSpec) -> str:
        models = []
        for node in spec.topological_order():
            if node.is_source():
                continue
            m: dict = {"name": node.name, "description": f"Generated from {node.transform_type.value} transform"}
            if node.output_schema:
                m["columns"] = [
                    {
                        "name": f.name,
                        "description": f"{f.dtype.value} field",
                        "tests": (["not_null"] if not f.nullable else []),
                    }
                    for f in node.output_schema.fields
                ]
            models.append(m)

        doc = {"version": 2, "models": models}
        return yaml.dump(doc, default_flow_style=False, sort_keys=False)

    def _generate_sources_yml(self, spec: PipelineSpec) -> str:
        tables = []
        for node in spec.sources():
            t: dict = {"name": node.name}
            if node.output_schema:
                t["columns"] = [{"name": f.name, "description": f.dtype.value} for f in node.output_schema.fields]
            tables.append(t)

        doc = {
            "version": 2,
            "sources": [{"name": spec.name, "tables": tables}],
        }
        return yaml.dump(doc, default_flow_style=False, sort_keys=False)

    def _generate_dbt_project(self, spec: PipelineSpec) -> str:
        doc = {
            "name": spec.name.replace("-", "_"),
            "version": "1.0.0",
            "config-version": 2,
            "profile": spec.name.replace("-", "_"),
            "model-paths": ["models"],
            "models": {
                spec.name.replace("-", "_"): {
                    "+materialized": "table",
                }
            },
        }
        return yaml.dump(doc, default_flow_style=False, sort_keys=False)
