"""Generate PyFlink (Table API) code from a PipelineSpec."""
from __future__ import annotations

from textwrap import indent

from ..dsl.ir import PipelineSpec, TransformNode
from ..dsl.types import AggFunction, TransformType
from ..compiler.selector import Target
from .base import BaseTarget, CompiledArtifact


_AGG_SQL = {
    AggFunction.COUNT: "COUNT",
    AggFunction.SUM: "SUM",
    AggFunction.AVG: "AVG",
    AggFunction.MIN: "MIN",
    AggFunction.MAX: "MAX",
    AggFunction.FIRST: "FIRST_VALUE",
    AggFunction.LAST: "LAST_VALUE",
    AggFunction.COUNT_DISTINCT: "COUNT(DISTINCT",
}

_FLINK_TYPE_MAP = {
    "string": "DataTypes.STRING()",
    "integer": "DataTypes.INT()",
    "long": "DataTypes.BIGINT()",
    "float": "DataTypes.FLOAT()",
    "double": "DataTypes.DOUBLE()",
    "boolean": "DataTypes.BOOLEAN()",
    "timestamp": "DataTypes.TIMESTAMP(3)",
    "date": "DataTypes.DATE()",
    "bytes": "DataTypes.BYTES()",
}


class FlinkTarget(BaseTarget):
    def generate(self, spec: PipelineSpec) -> CompiledArtifact:
        lines: list[str] = []
        compiled_nodes: list[dict] = []

        lines += [
            "# Auto-generated by pipeline-topology-compiler — DO NOT EDIT",
            f"# Pipeline: {spec.name}",
            f"# Target:   Flink (PyFlink Table API)",
            f"# SLA:      latency={spec.sla.max_latency}, size={spec.sla.dataset_size}",
            "",
            "from pyflink.datastream import StreamExecutionEnvironment",
            "from pyflink.table import StreamTableEnvironment, EnvironmentSettings",
            "from pyflink.table.types import DataTypes",
            "from pyflink.table import Schema as FlinkSchema",
            "",
            "",
            "def build_pipeline() -> StreamTableEnvironment:",
            f'    """Pipeline: {spec.name}',
            "",
            f"    {spec.description}",
            '    """',
            "    env = StreamExecutionEnvironment.get_execution_environment()",
            "    env.set_parallelism(4)",
            "    settings = EnvironmentSettings.in_streaming_mode()",
            "    t_env = StreamTableEnvironment.create(env, settings)",
            "    tables = {}",
            "",
        ]

        for node in spec.topological_order():
            snippet, meta = self._node_to_flink(node)
            lines.append(indent(snippet, "    "))
            lines.append("")
            compiled_nodes.append(meta)

        lines += [
            "    return t_env, tables",
            "",
            "",
            'if __name__ == "__main__":',
            "    t_env, tables = build_pipeline()",
            "    t_env.execute(" + repr(spec.name) + ")",
        ]

        code = "\n".join(lines)
        return CompiledArtifact(
            target=Target.FLINK,
            spec_name=spec.name,
            files={f"{spec.name}_flink.py": code},
            compiled_nodes=compiled_nodes,
        )

    def _node_to_flink(self, node: TransformNode) -> tuple[str, dict]:
        meta = {
            "name": node.name,
            "transform_type": node.transform_type.value,
            "inputs": node.inputs,
            "predicate": node.predicate,
            "columns": node.columns,
            "group_by": node.group_by,
            "aggregations": [
                {"name": a.output_name, "function": a.function.value, "column": a.column}
                for a in node.aggregations
            ],
            "join_type": node.join_type.value if node.join_on else None,
            "join_on": node.join_on,
            "window_column": node.window_column,
            "window_duration": node.window_duration,
        }

        if node.transform_type == TransformType.SOURCE:
            return self._source(node), meta
        if node.transform_type == TransformType.FILTER:
            return self._filter(node), meta
        if node.transform_type == TransformType.SELECT:
            return self._select(node), meta
        if node.transform_type == TransformType.MAP:
            return self._map(node), meta
        if node.transform_type == TransformType.JOIN:
            return self._join(node), meta
        if node.transform_type == TransformType.AGGREGATE:
            return self._aggregate(node), meta
        if node.transform_type == TransformType.UNION:
            return self._union(node), meta
        if node.transform_type == TransformType.WINDOW:
            return self._window_agg(node), meta
        if node.transform_type == TransformType.SINK:
            return self._sink(node), meta
        return f"# TODO: {node.name}", meta

    def _source(self, node: TransformNode) -> str:
        schema_lines = []
        if node.output_schema:
            for f in node.output_schema.fields:
                ftype = _FLINK_TYPE_MAP.get(f.dtype.value, "DataTypes.STRING()")
                null = "" if f.nullable else ".not_null()"
                schema_lines.append(f'            DataTypes.FIELD("{f.name}", {ftype}{null}),')

        schema_block = "\n".join(schema_lines)
        fmt = node.format or "filesystem"
        loc = node.location or f"/data/{node.name}"

        return (
            f"# Source: {node.name}\n"
            f't_env.execute_sql(f"""\n'
            f"    CREATE TABLE {node.name} (\n"
            + "".join(f"        {f.name} {self._sql_type(f.dtype.value)} {'NOT NULL' if not (node.output_schema and node.output_schema.get_field(f.name) and node.output_schema.get_field(f.name).nullable) else ''},\n" for f in (node.output_schema.fields if node.output_schema else []))
            + f"        watermark_for_event_time AS event_time - INTERVAL '5' SECOND\n"
            f"    ) WITH (\n"
            f"        'connector' = '{fmt}',\n"
            f"        'path' = '{loc}',\n"
            f"        'format' = 'json'\n"
            f"    )\n"
            f'""")\n'
            f'tables["{node.name}"] = t_env.from_path("{node.name}")'
        )

    def _sql_type(self, dtype: str) -> str:
        return {
            "string": "STRING", "integer": "INT", "long": "BIGINT",
            "float": "FLOAT", "double": "DOUBLE", "boolean": "BOOLEAN",
            "timestamp": "TIMESTAMP(3)", "date": "DATE", "bytes": "BYTES",
        }.get(dtype, "STRING")

    def _filter(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        return (
            f"# Filter: {node.name}\n"
            f'tables["{node.name}"] = tables["{inp}"].filter({repr(node.predicate)})'
        )

    def _select(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        cols = ", ".join(node.columns or [])
        return (
            f"# Select: {node.name}\n"
            f'tables["{node.name}"] = tables["{inp}"].select("{cols}")'
        )

    def _map(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        exprs = ", ".join(f"{v} AS {k}" for k, v in node.expressions.items())
        return (
            f"# Map: {node.name}\n"
            f'tables["{node.name}"] = tables["{inp}"].add_columns({repr(exprs)})'
        )

    def _join(self, node: TransformNode) -> str:
        left, right = node.inputs[0], node.inputs[1]
        cond = node.join_on or "???"
        jtype = node.join_type.value.upper()
        sql = (
            f"SELECT * FROM {left} "
            f"{jtype} JOIN {right} ON {cond}"
        )
        return (
            f"# Join: {node.name}\n"
            f'tables["{node.name}"] = t_env.sql_query({repr(sql)})'
        )

    def _aggregate(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        gb = ", ".join(node.group_by)
        aggs = []
        for a in node.aggregations:
            fn = _AGG_SQL.get(a.function, "COUNT")
            col = a.column or "*"
            if a.function == AggFunction.COUNT_DISTINCT:
                aggs.append(f"COUNT(DISTINCT {col}) AS {a.output_name}")
            else:
                aggs.append(f"{fn}({col}) AS {a.output_name}")

        select_cols = (f"{gb}, " if gb else "") + ", ".join(aggs)
        sql = f"SELECT {select_cols} FROM {inp}" + (f" GROUP BY {gb}" if gb else "")
        return (
            f"# Aggregate: {node.name}\n"
            f'tables["{node.name}"] = t_env.sql_query({repr(sql)})'
        )

    def _union(self, node: TransformNode) -> str:
        sql = " UNION ALL ".join(f"SELECT * FROM {inp}" for inp in node.inputs)
        return (
            f"# Union: {node.name}\n"
            f'tables["{node.name}"] = t_env.sql_query({repr(sql)})'
        )

    def _window_agg(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        time_col = node.window_column or "event_time"
        duration = node.window_duration or "1 HOUR"
        slide = node.slide_duration

        if slide:
            window_fn = f"HOP({time_col}, INTERVAL '{slide}', INTERVAL '{duration}')"
        else:
            window_fn = f"TUMBLE({time_col}, INTERVAL '{duration}')"

        gb = ", ".join(node.group_by)
        aggs = []
        for a in node.aggregations:
            fn = _AGG_SQL.get(a.function, "COUNT")
            col = a.column or "*"
            aggs.append(f"{fn}({col}) AS {a.output_name}")

        gb_full = (f"{gb}, " if gb else "") + "window_start, window_end"
        select_cols = gb_full + ", " + ", ".join(aggs)
        sql = (
            f"SELECT {select_cols} "
            f"FROM TABLE({window_fn} TABLE {inp}) "
            + (f"GROUP BY {gb_full}" if node.group_by or aggs else "")
        )
        return (
            f"# Window aggregate: {node.name}\n"
            f'tables["{node.name}"] = t_env.sql_query({repr(sql)})'
        )

    def _sink(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        fmt = node.format or "filesystem"
        loc = node.location or f"/output/{node.name}"
        return (
            f"# Sink: {node.name}\n"
            f't_env.execute_sql(f"""\n'
            f"    CREATE TABLE {node.name}_sink (\n"
            f"        `__placeholder__` STRING\n"
            f"    ) WITH (\n"
            f"        'connector' = '{fmt}',\n"
            f"        'path' = '{loc}',\n"
            f"        'format' = 'json'\n"
            f"    )\n"
            f'""")\n'
            f'tables["{inp}"].execute_insert("{node.name}_sink")'
        )
