"""Generate PySpark (DataFrame API) code from a PipelineSpec."""
from __future__ import annotations

from textwrap import indent, dedent
from typing import Optional

from ..dsl.ir import PipelineSpec, TransformNode
from ..dsl.types import AggFunction, TransformType
from ..compiler.selector import Target
from .base import BaseTarget, CompiledArtifact


_AGG_MAP = {
    AggFunction.COUNT: "F.count",
    AggFunction.SUM: "F.sum",
    AggFunction.AVG: "F.avg",
    AggFunction.MIN: "F.min",
    AggFunction.MAX: "F.max",
    AggFunction.FIRST: "F.first",
    AggFunction.LAST: "F.last",
    AggFunction.COLLECT_LIST: "F.collect_list",
    AggFunction.COUNT_DISTINCT: "F.countDistinct",
}


class SparkTarget(BaseTarget):
    def generate(self, spec: PipelineSpec) -> CompiledArtifact:
        lines: list[str] = []
        compiled_nodes: list[dict] = []

        lines += [
            "# Auto-generated by pipeline-topology-compiler — DO NOT EDIT",
            f"# Pipeline: {spec.name}",
            f"# Target:   Spark (PySpark DataFrame API)",
            f"# SLA:      latency={spec.sla.max_latency}, size={spec.sla.dataset_size}",
            "",
            "from pyspark.sql import SparkSession",
            "import pyspark.sql.functions as F",
            "from pyspark.sql.types import (",
            "    StructType, StructField,",
            "    StringType, IntegerType, LongType, FloatType, DoubleType,",
            "    BooleanType, TimestampType, DateType, BinaryType,",
            ")",
            "",
            "",
            "def build_pipeline(spark: SparkSession) -> dict:",
            f'    """Pipeline: {spec.name}',
            f"",
            f"    {spec.description}",
            f'    """',
            "    dfs = {}",
            "",
        ]

        for node in spec.topological_order():
            snippet, meta = self._node_to_spark(node)
            lines.append(indent(snippet, "    "))
            lines.append("")
            compiled_nodes.append(meta)

        lines += [
            "    return dfs",
            "",
            "",
            "if __name__ == '__main__':",
            "    spark = SparkSession.builder.appName(" + repr(spec.name) + ").getOrCreate()",
            "    result = build_pipeline(spark)",
            "    for name, df in result.items():",
            "        print(f'{name}: {df.count()} rows')",
        ]

        code = "\n".join(lines)
        return CompiledArtifact(
            target=Target.SPARK,
            spec_name=spec.name,
            files={f"{spec.name}_spark.py": code},
            compiled_nodes=compiled_nodes,
        )

    def _node_to_spark(self, node: TransformNode) -> tuple[str, dict]:
        meta = {
            "name": node.name,
            "transform_type": node.transform_type.value,
            "inputs": node.inputs,
            "predicate": node.predicate,
            "columns": node.columns,
            "group_by": node.group_by,
            "aggregations": [
                {"name": a.output_name, "function": a.function.value, "column": a.column}
                for a in node.aggregations
            ],
            "join_type": node.join_type.value if node.join_on else None,
            "join_on": node.join_on,
        }

        if node.transform_type == TransformType.SOURCE:
            return self._source(node), meta

        if node.transform_type == TransformType.FILTER:
            return self._filter(node), meta

        if node.transform_type == TransformType.SELECT:
            return self._select(node), meta

        if node.transform_type == TransformType.MAP:
            return self._map(node), meta

        if node.transform_type == TransformType.JOIN:
            return self._join(node), meta

        if node.transform_type == TransformType.AGGREGATE:
            return self._aggregate(node), meta

        if node.transform_type == TransformType.UNION:
            return self._union(node), meta

        if node.transform_type == TransformType.WINDOW:
            return self._window(node), meta

        if node.transform_type == TransformType.SINK:
            return self._sink(node), meta

        return f"# TODO: {node.name} ({node.transform_type.value})", meta

    def _source(self, node: TransformNode) -> str:
        schema_str = self._schema_to_spark(node)
        fmt = node.format or "parquet"
        loc = node.location or f"/data/{node.name}"
        opts = node.options or {}
        opts_str = ", ".join(f'"{k}": "{v}"' for k, v in opts.items())

        lines = [f"# Source: {node.name}"]
        if schema_str:
            lines.append(schema_str)
            lines.append(
                f'dfs["{node.name}"] = spark.read.format("{fmt}")'
                + (f'.options(**{{{opts_str}}})' if opts_str else "")
                + f'.schema({node.name}_schema)'
                + f'.load("{loc}")'
            )
        else:
            lines.append(
                f'dfs["{node.name}"] = spark.read.format("{fmt}")'
                + f'.load("{loc}")'
            )
        return "\n".join(lines)

    def _schema_to_spark(self, node: TransformNode) -> str:
        if node.output_schema is None:
            return ""
        _type_map = {
            "string": "StringType()", "integer": "IntegerType()", "long": "LongType()",
            "float": "FloatType()", "double": "DoubleType()", "boolean": "BooleanType()",
            "timestamp": "TimestampType()", "date": "DateType()", "bytes": "BinaryType()",
        }
        fields = []
        for f in node.output_schema.fields:
            spark_type = _type_map.get(f.dtype.value, "StringType()")
            fields.append(f'    StructField("{f.name}", {spark_type}, {f.nullable}),')
        field_block = "\n".join(fields)
        return f"{node.name}_schema = StructType([\n{field_block}\n])"

    def _filter(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        return (
            f"# Filter: {node.name}\n"
            f'dfs["{node.name}"] = dfs["{inp}"].filter({repr(node.predicate)})'
        )

    def _select(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        cols = ", ".join(f'"{c}"' for c in (node.columns or []))
        return (
            f"# Select: {node.name}\n"
            f'dfs["{node.name}"] = dfs["{inp}"].select({cols})'
        )

    def _map(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        lines = [f"# Map: {node.name}", f'dfs["{node.name}"] = dfs["{inp}"]']
        for out_col, expr in node.expressions.items():
            lines[-1] += f'.withColumn("{out_col}", F.expr({repr(expr)}))'
        return "\n".join(lines)

    def _join(self, node: TransformNode) -> str:
        left, right = node.inputs[0], node.inputs[1]
        jtype = node.join_type.value
        cond = node.join_on or node.join_left_key or "???"
        return (
            f"# Join: {node.name}\n"
            f'dfs["{node.name}"] = dfs["{left}"].join(\n'
            f'    dfs["{right}"],\n'
            f'    on={repr(cond)},\n'
            f'    how="{jtype}",\n'
            f")"
        )

    def _aggregate(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        gb_cols = ", ".join(f'"{c}"' for c in node.group_by)
        agg_exprs = []
        for a in node.aggregations:
            func = _AGG_MAP.get(a.function, "F.count")
            col_arg = f'"{a.column}"' if a.column else '"*"'
            agg_exprs.append(f'{func}({col_arg}).alias("{a.output_name}")')
        agg_str = ",\n        ".join(agg_exprs)
        return (
            f"# Aggregate: {node.name}\n"
            f'dfs["{node.name}"] = (\n'
            f'    dfs["{inp}"]\n'
            f'    .groupBy({gb_cols})\n'
            f"    .agg(\n        {agg_str},\n    )\n"
            f")"
        )

    def _union(self, node: TransformNode) -> str:
        first, *rest = node.inputs
        chain = f'dfs["{first}"]'
        for r in rest:
            chain += f'.unionByName(dfs["{r}"])'
        return f"# Union: {node.name}\ndfs[\"{node.name}\"] = {chain}"

    def _window(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        time_col = node.window_column or "event_time"
        duration = node.window_duration or "1 hour"
        slide = node.slide_duration
        gb_cols = ", ".join(f'"{c}"' for c in node.group_by)
        agg_exprs = []
        for a in node.aggregations:
            func = _AGG_MAP.get(a.function, "F.count")
            col_arg = f'"{a.column}"' if a.column else '"*"'
            agg_exprs.append(f'{func}({col_arg}).alias("{a.output_name}")')

        window_call = f'F.window("{time_col}", "{duration}"'
        if slide:
            window_call += f', "{slide}"'
        window_call += ")"

        agg_str = ",\n        ".join(agg_exprs)
        gb_part = f", {gb_cols}" if gb_cols else ""

        return (
            f"# Window: {node.name}\n"
            f'dfs["{node.name}"] = (\n'
            f'    dfs["{inp}"]\n'
            f"    .groupBy({window_call}{gb_part})\n"
            f"    .agg(\n        {agg_str},\n    )\n"
            f")"
        )

    def _sink(self, node: TransformNode) -> str:
        inp = node.inputs[0]
        fmt = node.format or "parquet"
        loc = node.location or f"/output/{node.name}"
        return (
            f"# Sink: {node.name}\n"
            f'dfs["{node.name}"] = dfs["{inp}"]\n'
            f'dfs["{node.name}"].write.format("{fmt}").mode("overwrite").save("{loc}")'
        )
