apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autoscaler-data
  namespace: autoscaler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
