"""dbt code generator — one dbt model file."""

from __future__ import annotations

from typing import TYPE_CHECKING

from ppc.codegen.sql_codegen import emit_sql

if TYPE_CHECKING:
    from ppc.ir.physical import PhysicalPlan


def emit_dbt(plan: PhysicalPlan, model_name: str = "ppc_output") -> str:
    """Render as a dbt model (.sql file)."""
    sql = emit_sql(plan.root, dialect="ansi")
    return f'''-- Auto-generated by physical-plan-compiler.
-- Engine: dbt | model: {model_name}
-- Estimated total cost: {plan.total_cost:.2f}

{{{{ config(
    materialized="table",
    tags=["ppc-generated"],
) }}}}

{sql}
'''
