"""DuckDB code generator.

DuckDB is a SQL-speaking engine; we delegate to the generic SQL emitter
and just wrap the result with engine-appropriate boilerplate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from ppc.codegen.sql_codegen import emit_sql

if TYPE_CHECKING:
    from ppc.ir.physical import PhysicalPlan


def emit_duckdb(plan: PhysicalPlan) -> str:
    """Emit a DuckDB Python script that runs the plan."""
    sql = emit_sql(plan.root, dialect="duckdb")
    return f'''"""Auto-generated by physical-plan-compiler. Engine: DuckDB.

Estimated total cost: {plan.total_cost:.2f}
"""
import duckdb

QUERY = """\n{sql}\n"""

if __name__ == "__main__":
    con = duckdb.connect(":memory:")
    # NOTE: you must attach / create the source tables before running this.
    result = con.execute(QUERY).fetchall()
    print(result)
'''
