"""Flink SQL code generator.

We emit Flink SQL (since Flink Table API is essentially SQL with extensions).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from ppc.codegen.sql_codegen import emit_sql

if TYPE_CHECKING:
    from ppc.ir.physical import PhysicalPlan


def emit_flink(plan: PhysicalPlan) -> str:
    sql = emit_sql(plan.root, dialect="ansi")
    return f'''-- Auto-generated by physical-plan-compiler. Engine: Flink SQL.
-- Estimated total cost: {plan.total_cost:.2f}

INSERT INTO sink_table
{sql};
'''
