"""PySpark code generator.

Emits a Python script that uses PySpark's DataFrame API. We could also
emit Spark SQL, but DataFrame is more idiomatic for compiled pipelines.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from ppc.engines.physical_ops import (
    PhysicalAggregate,
    PhysicalConversion,
    PhysicalFilter,
    PhysicalHashJoin,
    PhysicalScan,
)
from ppc.ir.expr import BinaryOp, ColumnRef, Expr, Literal, UnaryOp

if TYPE_CHECKING:
    from ppc.ir.physical import PhysicalNode, PhysicalPlan

_SPARK_OP = {
    "=": "==", "!=": "!=", "<": "<", "<=": "<=", ">": ">", ">=": ">=",
    "+": "+", "-": "-", "*": "*", "/": "/", "%": "%",
    "AND": "&", "OR": "|",
}


def _expr_to_spark(e: Expr) -> str:
    if isinstance(e, Literal):
        if isinstance(e.value, str):
            return repr(e.value)
        return repr(e.value)
    if isinstance(e, ColumnRef):
        return f'F.col("{e.name}")'
    if isinstance(e, BinaryOp):
        if e.op in {"AND", "OR"}:
            # Spark uses & and | with parens
            return f"(({_expr_to_spark(e.left)}) {_SPARK_OP[e.op]} ({_expr_to_spark(e.right)}))"
        return f"({_expr_to_spark(e.left)} {_SPARK_OP[e.op]} {_expr_to_spark(e.right)})"
    if isinstance(e, UnaryOp) and e.op == "NOT":
        return f"~({_expr_to_spark(e.operand)})"
    raise NotImplementedError(f"_expr_to_spark: {type(e).__name__}")


def _emit_node(node: PhysicalNode, varname: str) -> tuple[list[str], str]:
    """Returns (statements, expression-returning-DataFrame variable).

    Each call assigns to `varname` and returns the new name to use upstream.
    """
    if isinstance(node, PhysicalScan):
        return ([f'{varname} = spark.read.format("parquet").load("{node.table}")'], varname)

    if isinstance(node, PhysicalFilter):
        (child,) = node.children
        child_stmts, child_var = _emit_node(child, f"{varname}_child")
        stmt = f"{varname} = {child_var}.filter({_expr_to_spark(node.predicate)})"
        return ([*child_stmts, stmt], varname)

    if isinstance(node, PhysicalAggregate):
        (child,) = node.children
        child_stmts, child_var = _emit_node(child, f"{varname}_child")
        groups = ", ".join(f'"{g.name}"' for g in node.group_by)
        agg_exprs = []
        for a in node.aggregates:
            if a.func == "COUNT" and a.arg is None:
                agg_exprs.append(f'F.count("*").alias("{a.alias}")')
            else:
                col = _expr_to_spark(a.arg) if a.arg else "F.lit(1)"
                agg_exprs.append(f'F.{a.func.lower()}({col}).alias("{a.alias}")')
        agg_csv = ", ".join(agg_exprs)
        if node.group_by:
            stmt = f"{varname} = {child_var}.groupBy({groups}).agg({agg_csv})"
        else:
            stmt = f"{varname} = {child_var}.agg({agg_csv})"
        return ([*child_stmts, stmt], varname)

    if isinstance(node, PhysicalHashJoin):
        left, right = node.children
        l_stmts, l_var = _emit_node(left, f"{varname}_l")
        r_stmts, r_var = _emit_node(right, f"{varname}_r")
        on_expr = _expr_to_spark(node.on)
        stmt = (
            f'{varname} = {l_var}.join({r_var}, on={on_expr}, '
            f'how="{node.join_type.lower()}")'
        )
        return (l_stmts + r_stmts + [stmt], varname)

    if isinstance(node, PhysicalConversion):
        # Conversion into Spark = read the materialised result.
        # We emit a placeholder; the conversion's source is assumed to have
        # been materialised by an upstream step.
        child_stmts, child_var = _emit_node(node.child, f"{varname}_in")
        # No-op when both ends are Spark; otherwise a real conversion would
        # write+read parquet. We document this in the comment.
        if node.src_engine == "spark":
            return ([*child_stmts, f"{varname} = {child_var}"], varname)
        return (
            [*child_stmts, f'{varname} = spark.read.parquet("/tmp/conversion_{node.src_engine}_to_spark.parquet")  # converted upstream'],
            varname,
        )

    raise NotImplementedError(f"PySpark emit: {type(node).__name__}")


def emit_spark(plan: PhysicalPlan) -> str:
    stmts, final = _emit_node(plan.root, "df")
    body = "\n    ".join(stmts)
    return f'''"""Auto-generated by physical-plan-compiler. Engine: PySpark.
Estimated total cost: {plan.total_cost:.2f}
"""
from pyspark.sql import SparkSession, functions as F


def run() -> None:
    spark = SparkSession.builder.appName("ppc-output").getOrCreate()
    {body}
    {final}.show()


if __name__ == "__main__":
    run()
'''
