version: "3.8"

services:
  localstack:
    image: localstack/localstack:3.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kms,s3
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-}
    volumes:
      - localstack_data:/var/lib/localstack
      - ./scripts/localstack_init.sh:/etc/localstack/init/ready.d/init.sh

volumes:
  localstack_data:
