#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER analytics WITH PASSWORD '${ANALYTICS_DB_PASSWORD}';
  CREATE DATABASE analytics OWNER analytics;

  CREATE USER airflow WITH PASSWORD '${AIRFLOW_DB_PASSWORD}';
  CREATE DATABASE airflow OWNER airflow;

  CREATE USER superset WITH PASSWORD '${SUPERSET_DB_PASSWORD}';
  CREATE DATABASE superset OWNER superset;

  CREATE USER bi_read WITH PASSWORD '${BI_READ_PASSWORD}';
EOSQL
